# Generated by Django 5.0.2 on 2024-02-15 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("end_active_date", models.DateTimeField(null=True)),
                ("bytes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("bytes", models.IntegerField(default=0)),
                ("metadata", models.TextField()),
                ("uintarray", models.TextField()),
                (
                    "docgrp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.documentgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examiner",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("docgrp", models.ManyToManyField(to="api.documentgroup")),
            ],
        ),
    ]
